name: Deploy Application

on:
  push:
    branches:
      - main  # Atau branch lain yang kamu pakai untuk deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js (misalnya untuk app JS)
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no username@your-server "cd /path/to/your/app && git pull && npm install && npm run build && pm2 restart your-app"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
